# Generated by Django 2.2 on 2021-08-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCiudad', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPais', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPresupuesto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRegion', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.IntegerField(default=0)),
                ('niños', models.IntegerField(default=0)),
                ('bebes', models.IntegerField(default=0)),
                ('traslados', models.BooleanField(default=False)),
                ('shows', models.BooleanField(default=False)),
                ('excursiones', models.BooleanField(default=False)),
                ('con_guia', models.BooleanField(default=False)),
                ('sin_guia', models.BooleanField(default=False)),
                ('regular', models.BooleanField(default=False)),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='presupuesto', to='destinations.Presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudad', to='destinations.City')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais', to='destinations.Country')),
                ('prueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prueba', to='destinations.Prueba')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region', to='destinations.Region')),
            ],
        ),
    ]
