# Generated by Django 2.2 on 2020-11-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20201025_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='programa',
        ),
    ]
