# Generated by Django 2.2 on 2020-12-22 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destination_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='destinations.Region'),
        ),
    ]
