# Generated by Django 2.2 on 2020-12-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20201222_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudad', to='destinations.City'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais', to='destinations.Country'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region', to='destinations.Region'),
        ),
    ]
