# Generated by Django 2.2 on 2020-12-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_auto_20201228_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
