# Generated by Django 2.2 on 2021-09-01 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prueba_POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.IntegerField(default=0)),
                ('bebes', models.IntegerField(default=0)),
                ('conGuia', models.BooleanField(default=False)),
                ('confort', models.BooleanField(default=False)),
                ('destinationFromSearch', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('doble', models.BooleanField(default=False)),
                ('duracion', models.IntegerField(default=0)),
                ('estandar', models.BooleanField(default=False)),
                ('excursiones', models.BooleanField(default=False)),
                ('lujo', models.BooleanField(default=False)),
                ('mediaPension', models.BooleanField(default=False)),
                ('niños', models.IntegerField(default=0)),
                ('pensionCompleta', models.BooleanField(default=False)),
                ('presupuesto', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('regular', models.BooleanField(default=False)),
                ('selectedDateEnd', models.DateTimeField()),
                ('selectedDateStart', models.DateTimeField()),
                ('shows', models.BooleanField(default=False)),
                ('sinGuia', models.BooleanField(default=False)),
                ('single', models.BooleanField(default=False)),
                ('soloDesayuno', models.BooleanField(default=False)),
                ('traslados', models.BooleanField(default=False)),
                ('triple', models.BooleanField(default=False)),
            ],
        ),
    ]
