# Generated by Django 2.2 on 2021-08-22 23:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_POST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba_POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.IntegerField()),
                ('bebes', models.IntegerField()),
                ('conGuia', models.BooleanField(default=False)),
                ('confort', models.BooleanField(default=False)),
                ('destinationFromSearch', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), size=None)),
                ('doble', models.BooleanField(default=False)),
                ('duracion', models.IntegerField()),
                ('estandar', models.BooleanField(default=False)),
                ('excursiones', models.BooleanField(default=False)),
                ('lujo', models.BooleanField(default=False)),
                ('mediaPension', models.BooleanField(default=False)),
                ('niños', models.IntegerField()),
                ('pensionCompleta', models.BooleanField(default=False)),
                ('presupuesto', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('regular', models.BooleanField(default=False)),
                ('selectedDateEnd', models.DateTimeField()),
                ('selectedDateStart', models.DateTimeField()),
                ('shows', models.BooleanField(default=False)),
                ('sinGuia', models.BooleanField(default=False)),
                ('single', models.BooleanField(default=False)),
                ('soloDesayuno', models.BooleanField(default=False)),
                ('traslados', models.BooleanField(default=False)),
                ('triple', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='adultos',
        ),
        migrations.DeleteModel(
            name='bebes',
        ),
        migrations.DeleteModel(
            name='confort',
        ),
        migrations.DeleteModel(
            name='conGuia',
        ),
        migrations.DeleteModel(
            name='destinationFromSearch',
        ),
        migrations.DeleteModel(
            name='doble',
        ),
        migrations.DeleteModel(
            name='duracion',
        ),
        migrations.DeleteModel(
            name='estandar',
        ),
        migrations.DeleteModel(
            name='excursiones',
        ),
        migrations.DeleteModel(
            name='lujo',
        ),
        migrations.DeleteModel(
            name='mediaPension',
        ),
        migrations.DeleteModel(
            name='niños',
        ),
        migrations.DeleteModel(
            name='pensionCompleta',
        ),
        migrations.DeleteModel(
            name='presupuesto',
        ),
        migrations.DeleteModel(
            name='regular',
        ),
        migrations.DeleteModel(
            name='selectedDateEnd',
        ),
        migrations.DeleteModel(
            name='selectedDateStart',
        ),
        migrations.DeleteModel(
            name='shows',
        ),
        migrations.DeleteModel(
            name='single',
        ),
        migrations.DeleteModel(
            name='sinGuia',
        ),
        migrations.DeleteModel(
            name='soloDesayuno',
        ),
        migrations.DeleteModel(
            name='traslados',
        ),
        migrations.DeleteModel(
            name='triple',
        ),
    ]
