# Generated by Django 2.2 on 2021-08-23 00:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_POST', '0002_auto_20210822_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba_post',
            name='destinationFromSearch',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='prueba_post',
            name='presupuesto',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
