# Generated by Django 2.2 on 2021-08-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_POST', '0003_auto_20210822_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba_post',
            name='adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prueba_post',
            name='bebes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prueba_post',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prueba_post',
            name='niños',
            field=models.IntegerField(default=0),
        ),
    ]
