# Generated by Django 2.2 on 2020-11-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destination_programa'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='destinos',
            field=models.ManyToManyField(blank=True, related_name='destinos', to='destinations.Destination'),
        ),
    ]
