# Generated by Django 2.2 on 2021-08-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('descripcion', models.CharField(max_length=1000)),
                ('duracion', models.IntegerField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='services.Language')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='programs.Program')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='programs.Program')),
                ('tipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.TravelerType')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.FoodService')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.RoomType')),
                ('perfil_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.TripProfile')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='programs.Program')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.RoomType')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Activity')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='NoInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_incluidos', to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario', to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incluidos', to='programs.Program')),
            ],
        ),
    ]
