# Generated by Django 2.2 on 2020-10-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='include',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incluidos', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='noinclude',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_incluidos', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='programactivity',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='programcost',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='programquantity',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='programs.Program'),
        ),
    ]
