# Generated by Django 2.2 on 2020-11-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destination_programa'),
        ('programs', '0002_auto_20201025_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='programs.Program')),
            ],
        ),
    ]
