# Generated by Django 2.2 on 2020-12-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_activity_destinos'),
        ('programs', '0003_programdestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='programs.Program')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.FoodService')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.RoomType')),
                ('perfil_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.TripProfile')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='programs.Program')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType')),
            ],
        ),
    ]
